name: emb
channels:
  - conda-forge
  - defaults
dependencies:
  - colorama=0.4.6
  - colormath=3.0.0
  - imageio=2
  - ipykernel
  - matplotlib
  - numba
  - numpy=1
  - ply
  - pip
  - python=3.10
  - scikit-image
  - scikit-learn
  - scipy=1.12
  - tqdm
  - pip:
      - pyembroidery==1.4.36
      - svgelements
      - triangle==20220202
